version: '3.8'

services:

  maintenance:
    build:
      context: ./
      dockerfile: maintenance.dockerfile
    restart: always
    volumes:
      - ./docker/volumes/maintenance/certbot:/var/certbot/
      - ./docker/volumes/maintenance/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - nginx

  nginx:
    image: nginx:1.23
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/volumes/maintenance/certbot:/var/certbot/
      - ./docker/volumes/maintenance/letsencrypt/:/etc/nginx/ssl/
    depends_on:
      - node
    restart: "always"

  node:
    build:
      context: ./
      dockerfile: node.dockerfile
    depends_on:
      - mongo
      - peer
    restart: "always"

  mongo:
    image: mongo:6.0.6
    ports:
      - 27017:27017
    volumes:
      - ./docker/volumes/mongo:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prism
      MONGO_INITDB_ROOT_PASSWORD: password

  peer:
    image: peerjs/peerjs-server:1.0.0
    ports:
      - 9000:9000
    restart: "always"
