name: Deploy Image to GHCR

run-name: Deploy Image to GHCR!

on:
  push:
    tags:
      - 'v*'

jobs:
  push-store-image:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Main Branch"
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get Current Commit Tag
        id: tag
        uses: devops-actions/action-get-tag@v1.0.1
        with:
          strip_v: true
          default: v0.0.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build and Tag Image"
        run: |
          docker build . -t prismlabsdev/prismchat-api-node:${{ steps.tag.outputs.tag }}
          docker tag prismlabsdev/prismchat-api-node:${{ steps.tag.outputs.tag }} prismlabsdev/prismchat-api-node:latest

      - name: "Push Image to GHCR"
        run: |
          docker push prismlabsdev/prismchat-api-node:${{ steps.tag.outputs.tag }}
          docker push prismlabsdev/prismchat-api-node:latest
